//TODO: SET_LOADING, SET_CONTACT,
// CONTACT_TO_UPDATE, SET_SINGLE_CONTACT

export const SET_LOADING = 'SET_LOADING';
export const SET_FOODS = 'SET_FOODS';
export const CONTACT_TO_UPDATE = 'CONTACT_TO_UPDATE';
export const SET_SINGLE_CONTACT = 'SET_SINGLE_CONTACT';
export const SET_FOOD_IN_BASKET = 'SET_FOOD_IN_BASKET';
export const INCREASE_FOOD_IN_BASKET = 'INCREASE_FOOD_IN_BASKET';
export const DECREASE_FOOD_IN_BASKET = 'DECREASE_FOOD_IN_BASKET';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
